// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC86M5LOcmXXmm0U2Cu1D6lw2slSHteFNI',
    appId: '1:472398469167:web:afd368cfec4f0790aa0eda',
    messagingSenderId: '472398469167',
    projectId: 'health-5fdfb',
    authDomain: 'health-5fdfb.firebaseapp.com',
    storageBucket: 'health-5fdfb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWsmquBMKaAE615KlPztdUV7Ldr84zfMw',
    appId: '1:472398469167:android:3e4b39a745262d14aa0eda',
    messagingSenderId: '472398469167',
    projectId: 'health-5fdfb',
    storageBucket: 'health-5fdfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWGWplNQEYHunlCwHaIxltjTc96QVcdXU',
    appId: '1:472398469167:ios:7159a5ed258b2ee0aa0eda',
    messagingSenderId: '472398469167',
    projectId: 'health-5fdfb',
    storageBucket: 'health-5fdfb.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWGWplNQEYHunlCwHaIxltjTc96QVcdXU',
    appId: '1:472398469167:ios:8cdbfe508541726aaa0eda',
    messagingSenderId: '472398469167',
    projectId: 'health-5fdfb',
    storageBucket: 'health-5fdfb.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
